baseURL = "https://blog.cruru.kr/"
languageCode = "en-us"
title = "Team Cruru. Dev Blog"

[module]
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
#    replacements = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5 -> hugo-mod-bootstrap-scss"
#    [[module.imports]]
#        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
#        disable = false
